<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c5b208c9-4528-4dfb-896d-bc35c749a2e2</UserSecretsId>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiCisco\ApiCisco.csproj" />
    <ProjectReference Include="..\ApiEVE\ApiEVE.csproj" />
    <ProjectReference Include="..\BusinessLayer\BusinessLayer.csproj" />
    <ProjectReference Include="..\TelnetConsole\TelnetConsole.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="bootstrap" Version="5.3.8" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\SharedResource.cs.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SharedResource.cs.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SharedResource.en.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SharedResource.en.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SharedResource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SharedResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\SharedResource.cs.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharedResource.cs.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SharedResource.en.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharedResource.en.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SharedResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharedResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
