//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetResVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_cs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_cs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetResVM.Web.Resources.SharedResource.cs", typeof(SharedResource_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přístup odepřen. Chcete-li tuto funkci použít, přihlaste se..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přístup odepřen. Je vyžadována role správce..
        /// </summary>
        internal static string AccessDeniedAdmin {
            get {
                return ResourceManager.GetString("AccessDeniedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolit.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolen.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte uživatelské jméno osoby, které chcete udělit přístup k této laboratoři.
        /// </summary>
        internal static string addcollabenterusername {
            get {
                return ResourceManager.GetString("addcollabenterusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat spolupracovníka.
        /// </summary>
        internal static string AddCollaborator {
            get {
                return ResourceManager.GetString("AddCollaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat nový server.
        /// </summary>
        internal static string AddNewServ {
            get {
                return ResourceManager.GetString("AddNewServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat uživatele.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala chyba. Kontaktujte administrátora..
        /// </summary>
        internal static string AnErrorOccured {
            get {
                return ResourceManager.GetString("AnErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ověření se nezdařilo:.
        /// </summary>
        internal static string AuthFailed {
            get {
                return ResourceManager.GetString("AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string AuthorLab {
            get {
                return ResourceManager.GetString("AuthorLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ autorizace.
        /// </summary>
        internal static string AuthType {
            get {
                return ResourceManager.GetString("AuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět na výpis laboratoří.
        /// </summary>
        internal static string BackToLabList {
            get {
                return ResourceManager.GetString("BackToLabList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazání zálohy se nezdařilo..
        /// </summary>
        internal static string BackupDeleteFailed {
            get {
                return ResourceManager.GetString("BackupDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze smazat zálohu laboratoře... Tato laboratoř není ve vašem vlastnictví..
        /// </summary>
        internal static string BackupDeleteFailNotOwned {
            get {
                return ResourceManager.GetString("BackupDeleteFailNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záloha byla smazána..
        /// </summary>
        internal static string BackupDeleteSuccess {
            get {
                return ResourceManager.GetString("BackupDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stažení zálohy se nezdařilo..
        /// </summary>
        internal static string BackupDownloadFailed {
            get {
                return ResourceManager.GetString("BackupDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zálohování se nezdařilo..
        /// </summary>
        internal static string BackupFailed {
            get {
                return ResourceManager.GetString("BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zálohovat laboratoř.
        /// </summary>
        internal static string BackupLab {
            get {
                return ResourceManager.GetString("BackupLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obnovení se nezdařilo.
        /// </summary>
        internal static string BackupRestoreFailed {
            get {
                return ResourceManager.GetString("BackupRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze obnovit zálohu laboratoře... Tato laboratoř není ve vašem vlastnictví..
        /// </summary>
        internal static string BackupRestoreFailNotOwned {
            get {
                return ResourceManager.GetString("BackupRestoreFailNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obnovení laboratoře proběhlo úspěšně..
        /// </summary>
        internal static string BackupRestoreSuccess {
            get {
                return ResourceManager.GetString("BackupRestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zálohy.
        /// </summary>
        internal static string BackupsLayout {
            get {
                return ResourceManager.GetString("BackupsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zálohování proběhlo úspěšně..
        /// </summary>
        internal static string BackupSuccess {
            get {
                return ResourceManager.GetString("BackupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        internal static string CancelB {
            get {
                return ResourceManager.GetString("CancelB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna hesla.
        /// </summary>
        internal static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna hesla pro uživatele LDAP je nedostupná.
        /// </summary>
        internal static string ChangePassLDAP {
            get {
                return ResourceManager.GetString("ChangePassLDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdit nové heslo.
        /// </summary>
        internal static string ConfirmNewPass {
            get {
                return ResourceManager.GetString("ConfirmNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připojit k serveru.
        /// </summary>
        internal static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připojení se nezdařilo..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připojení bylo přerušeno! Během vaší práce došlo k výpadku serveru..
        /// </summary>
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připojení proběhlo úspěšně..
        /// </summary>
        internal static string ConnectionSuccess {
            get {
                return ResourceManager.GetString("ConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořeno dne.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spolupracovníci.
        /// </summary>
        internal static string CurrentCollaborators {
            get {
                return ResourceManager.GetString("CurrentCollaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakázat.
        /// </summary>
        internal static string DeactivateButton {
            get {
                return ResourceManager.GetString("DeactivateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete tuto laboratoř trvale smazat?.
        /// </summary>
        internal static string DeleteConfirmLab {
            get {
                return ResourceManager.GetString("DeleteConfirmLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat laboratoř.
        /// </summary>
        internal static string DeleteLab {
            get {
                return ResourceManager.GetString("DeleteLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis laboratoře.
        /// </summary>
        internal static string DescriptionLab {
            get {
                return ResourceManager.GetString("DescriptionLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stáhnout laboratoř.
        /// </summary>
        internal static string DownloadLab {
            get {
                return ResourceManager.GetString("DownloadLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit server.
        /// </summary>
        internal static string EditServer {
            get {
                return ResourceManager.GetString("EditServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypršelé rezervace.
        /// </summary>
        internal static string ExpiredReservations {
            get {
                return ResourceManager.GetString("ExpiredReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervace, jejichž platnost vypršela, se po 6 měsících automaticky smažou.
        /// </summary>
        internal static string ExpiredResWarning {
            get {
                return ResourceManager.GetString("ExpiredResWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportovat.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor nenalezen..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pátek.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        internal static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecné informace.
        /// </summary>
        internal static string GeneralDetails {
            get {
                return ResourceManager.GetString("GeneralDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výběr serveru.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importovat laboratoř.
        /// </summary>
        internal static string ImportLab {
            get {
                return ResourceManager.GetString("ImportLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatné přihlašovací údaje.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný čas rezervace..
        /// </summary>
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP adresa serveru nebo URL.
        /// </summary>
        internal static string IPadd {
            get {
                return ResourceManager.GetString("IPadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratoř.
        /// </summary>
        internal static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při mazání laboratoře došlo k chybě..
        /// </summary>
        internal static string LabDeleteError {
            get {
                return ResourceManager.GetString("LabDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratoř byla smazána..
        /// </summary>
        internal static string LabDeleteSuccess {
            get {
                return ResourceManager.GetString("LabDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID laboratoře.
        /// </summary>
        internal static string LabId {
            get {
                return ResourceManager.GetString("LabId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratoř byla úspěšně importována..
        /// </summary>
        internal static string LabImportSuccess {
            get {
                return ResourceManager.GetString("LabImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info o laboratoři.
        /// </summary>
        internal static string LabInfo {
            get {
                return ResourceManager.GetString("LabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno laboratoře.
        /// </summary>
        internal static string LabName {
            get {
                return ResourceManager.GetString("LabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při načítání uzlů došlo k chybě..
        /// </summary>
        internal static string LabNodesError {
            get {
                return ResourceManager.GetString("LabNodesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevybrána laboratoř..
        /// </summary>
        internal static string LabNotSelected {
            get {
                return ResourceManager.GetString("LabNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastnictví laboratoře bylo úspěšně odstraněno..
        /// </summary>
        internal static string LabOwnedRemoved {
            get {
                return ResourceManager.GetString("LabOwnedRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastnictví laboratoře nebylo možné odstranit..
        /// </summary>
        internal static string LabOwnedRemoveError {
            get {
                return ResourceManager.GetString("LabOwnedRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratoř přiřazena..
        /// </summary>
        internal static string LabOwnedSuccess {
            get {
                return ResourceManager.GetString("LabOwnedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastníci laboratoří.
        /// </summary>
        internal static string LabOwners {
            get {
                return ResourceManager.GetString("LabOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratoř spuštěna..
        /// </summary>
        internal static string LabStartedSuccess {
            get {
                return ResourceManager.GetString("LabStartedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při spouštění laboratoře došlo k chybě..
        /// </summary>
        internal static string LabStartError {
            get {
                return ResourceManager.GetString("LabStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při zastavování laboratoře došlo k chybě..
        /// </summary>
        internal static string LabStopError {
            get {
                return ResourceManager.GetString("LabStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratoř zastavena..
        /// </summary>
        internal static string LabStoppedSuccess {
            get {
                return ResourceManager.GetString("LabStoppedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratoř s ID nebyla nalezena..
        /// </summary>
        internal static string LabWithIDNotFound {
            get {
                return ResourceManager.GetString("LabWithIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam.
        /// </summary>
        internal static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Místní.
        /// </summary>
        internal static string localhost {
            get {
                return ResourceManager.GetString("localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        internal static string LogoutLayout {
            get {
                return ResourceManager.GetString("LogoutLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa záloh.
        /// </summary>
        internal static string ManageBackup {
            get {
                return ResourceManager.GetString("ManageBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa spolupracovníků.
        /// </summary>
        internal static string ManageCollaborators {
            get {
                return ResourceManager.GetString("ManageCollaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa uživatelů.
        /// </summary>
        internal static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete tuto zálohu smazat? Tato akce je nevratná!.
        /// </summary>
        internal static string MessageWarningDeleteBackup {
            get {
                return ResourceManager.GetString("MessageWarningDeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete tuto zálohu obnovit? Tato operace přepíše aktuální stav laboratoře..
        /// </summary>
        internal static string MessageWarningRestoreBackup {
            get {
                return ResourceManager.GetString("MessageWarningRestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraveno.
        /// </summary>
        internal static string ModifiedLab {
            get {
                return ResourceManager.GetString("ModifiedLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pondělí.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalendář (aktuální měsíc).
        /// </summary>
        internal static string MonthView {
            get {
                return ResourceManager.GetString("MonthView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje laboratoře.
        /// </summary>
        internal static string MyLabLayout {
            get {
                return ResourceManager.GetString("MyLabLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje rezervace.
        /// </summary>
        internal static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo.
        /// </summary>
        internal static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit novou rezervaci.
        /// </summary>
        internal static string NewReservation {
            get {
                return ResourceManager.GetString("NewReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyly nalezeny žádné zálohy.
        /// </summary>
        internal static string NoBackups {
            get {
                return ResourceManager.GetString("NoBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatím nemáte žádného spolupracovníka.
        /// </summary>
        internal static string NoCollaboratorsYet {
            get {
                return ResourceManager.GetString("NoCollaboratorsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet uzlů.
        /// </summary>
        internal static string NodesCount {
            get {
                return ResourceManager.GetString("NodesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejsou k dispozici žádné rezervace s prošlou platností.
        /// </summary>
        internal static string NoExpired {
            get {
                return ResourceManager.GetString("NoExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro vybraný server nebyly nalezeny žádné laboratoře..
        /// </summary>
        internal static string NoLabsFound {
            get {
                return ResourceManager.GetString("NoLabsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikdo.
        /// </summary>
        internal static string NoneOwns {
            get {
                return ResourceManager.GetString("NoneOwns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatím nevlastníš žádné laboratoře..
        /// </summary>
        internal static string NoOwnedLab {
            get {
                return ResourceManager.GetString("NoOwnedLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádné plánované rezervace.
        /// </summary>
        internal static string NoReservation {
            get {
                return ResourceManager.GetString("NoReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Původní heslo.
        /// </summary>
        internal static string OldPass {
            get {
                return ResourceManager.GetString("OldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staré heslo je nesprávné..
        /// </summary>
        internal static string OldPassIcorrect {
            get {
                return ResourceManager.GetString("OldPassIcorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastnit laboratoř.
        /// </summary>
        internal static string OwnLab {
            get {
                return ResourceManager.GetString("OwnLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo bylo úspěšně změněno..
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo se nepodařilo změnit..
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesla se neshodují..
        /// </summary>
        internal static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro místní účet je nutné zadat heslo..
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Nechte prázdné, pokud chcete zachovat stávající).
        /// </summary>
        internal static string placeholderPass {
            get {
                return ResourceManager.GetString("placeholderPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plánované rezervace.
        /// </summary>
        internal static string PlannedReservations {
            get {
                return ResourceManager.GetString("PlannedReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifikace platformy.
        /// </summary>
        internal static string PlatformSpecifics {
            get {
                return ResourceManager.GetString("PlatformSpecifics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrat.
        /// </summary>
        internal static string RemoveCollab {
            get {
                return ResourceManager.GetString("RemoveCollab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrat vlastnictví.
        /// </summary>
        internal static string RemoveOwnership {
            get {
                return ResourceManager.GetString("RemoveOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervace byla vytvořena..
        /// </summary>
        internal static string ReservationCreated {
            get {
                return ResourceManager.GetString("ReservationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervace smazána..
        /// </summary>
        internal static string ReservationDeleted {
            get {
                return ResourceManager.GetString("ReservationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V současné době již existuje rezervace nebo došlo k chybě..
        /// </summary>
        internal static string ReservationExistsError {
            get {
                return ResourceManager.GetString("ReservationExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervace.
        /// </summary>
        internal static string ReservationLayout {
            get {
                return ResourceManager.GetString("ReservationLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervovat laboratoř.
        /// </summary>
        internal static string ReserveLab {
            get {
                return ResourceManager.GetString("ReserveLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervace musí být minimálně na 1 hodinu..
        /// </summary>
        internal static string ResOneHour {
            get {
                return ResourceManager.GetString("ResOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek a konec rezervace musí být ve stejný den..
        /// </summary>
        internal static string ResSameDay {
            get {
                return ResourceManager.GetString("ResSameDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobota.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit změny.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber laboratoř....
        /// </summary>
        internal static string SelectLab {
            get {
                return ResourceManager.GetString("SelectLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber platformu.
        /// </summary>
        internal static string SelectPlatform {
            get {
                return ResourceManager.GetString("SelectPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber server....
        /// </summary>
        internal static string SelectServer {
            get {
                return ResourceManager.GetString("SelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber zobrazení.
        /// </summary>
        internal static string SelectView {
            get {
                return ResourceManager.GetString("SelectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server byl úspěšně přidán..
        /// </summary>
        internal static string ServerAdded {
            get {
                return ResourceManager.GetString("ServerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno serveru.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server nelze přidat. Viz protokol..
        /// </summary>
        internal static string ServerNotAdded {
            get {
                return ResourceManager.GetString("ServerNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server neexistuje nebo došlo k chybě. Podívejte se do protokolu..
        /// </summary>
        internal static string ServerNotExist {
            get {
                return ResourceManager.GetString("ServerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server nebyl nalezen..
        /// </summary>
        internal static string ServerNotFound {
            get {
                return ResourceManager.GetString("ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevybrán server..
        /// </summary>
        internal static string ServerNotSelected {
            get {
                return ResourceManager.GetString("ServerNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server nelze aktualizovat. Viz protokol..
        /// </summary>
        internal static string ServerNotUpdated {
            get {
                return ResourceManager.GetString("ServerNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server je mimo provoz..
        /// </summary>
        internal static string ServerOffline {
            get {
                return ResourceManager.GetString("ServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server smazán..
        /// </summary>
        internal static string ServerRemoved {
            get {
                return ResourceManager.GetString("ServerRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforma.
        /// </summary>
        internal static string ServerType {
            get {
                return ResourceManager.GetString("ServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server aktualizován..
        /// </summary>
        internal static string ServerUpdated {
            get {
                return ResourceManager.GetString("ServerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit uzly.
        /// </summary>
        internal static string ShowNodes {
            get {
                return ResourceManager.GetString("ShowNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo k chybě. Podívejte se do protokolu..
        /// </summary>
        internal static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V provozu .
        /// </summary>
        internal static string StartedState {
            get {
                return ResourceManager.GetString("StartedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapnout laboratoř.
        /// </summary>
        internal static string StartLab {
            get {
                return ResourceManager.GetString("StartLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastavit laboratoř.
        /// </summary>
        internal static string StopLab {
            get {
                return ResourceManager.GetString("StopLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastaveno.
        /// </summary>
        internal static string StoppedState {
            get {
                return ResourceManager.GetString("StoppedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neděle.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ověřit připojení.
        /// </summary>
        internal static string TestConn {
            get {
                return ResourceManager.GetString("TestConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čtvrtek.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úterý.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámý.
        /// </summary>
        internal static string UnknownState {
            get {
                return ResourceManager.GetString("UnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodporovaná platforma..
        /// </summary>
        internal static string UnsupportedPlatform {
            get {
                return ResourceManager.GetString("UnsupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel byl úspěšně aktivován..
        /// </summary>
        internal static string UserActivated {
            get {
                return ResourceManager.GetString("UserActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel nemohl být aktivován..
        /// </summary>
        internal static string UserActivatedFail {
            get {
                return ResourceManager.GetString("UserActivatedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel nemohl být přidán..
        /// </summary>
        internal static string UserAddedFail {
            get {
                return ResourceManager.GetString("UserAddedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel byl úspěšně přidán..
        /// </summary>
        internal static string UserAddedSuccess {
            get {
                return ResourceManager.GetString("UserAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel byl úspěšně přidán jako spolupracovník..
        /// </summary>
        internal static string UserCollaboratorAdded {
            get {
                return ResourceManager.GetString("UserCollaboratorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel byl úspěšně deaktivován..
        /// </summary>
        internal static string UserDeactivated {
            get {
                return ResourceManager.GetString("UserDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel nemohl být deaktivován..
        /// </summary>
        internal static string UserDeactivatedFail {
            get {
                return ResourceManager.GetString("UserDeactivatedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel neexistuje..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel nebyl vybrán..
        /// </summary>
        internal static string UserNotSelected {
            get {
                return ResourceManager.GetString("UserNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel byl úspěšně odstraněn..
        /// </summary>
        internal static string UserRemoved {
            get {
                return ResourceManager.GetString("UserRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel nemohl být odstraněn. Viz protokol..
        /// </summary>
        internal static string UserRemovedFail {
            get {
                return ResourceManager.GetString("UserRemovedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Středa.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K otestování připojení potřebujete heslo..
        /// </summary>
        internal static string YouNeedPassword {
            get {
                return ResourceManager.GetString("YouNeedPassword", resourceCulture);
            }
        }
    }
}
