//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetResVM.Resources {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetResVM.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Access Denied.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný AccessDeniedAdmmin.
        /// </summary>
        internal static string AccessDeniedAdmin {
            get {
                return ResourceManager.GetString("AccessDeniedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Actionss.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ActivateB.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Activa.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný AddCollaboratorUsername.
        /// </summary>
        internal static string addcollabenterusername {
            get {
                return ResourceManager.GetString("addcollabenterusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný AddCollaborator.
        /// </summary>
        internal static string AddCollaborator {
            get {
                return ResourceManager.GetString("AddCollaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný AddNewServer.
        /// </summary>
        internal static string AddNewServ {
            get {
                return ResourceManager.GetString("AddNewServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add HIM.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný An error occurred..
        /// </summary>
        internal static string AnErrorOccured {
            get {
                return ResourceManager.GetString("AnErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný AuthFailed.
        /// </summary>
        internal static string AuthFailed {
            get {
                return ResourceManager.GetString("AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný AuthorLab.
        /// </summary>
        internal static string AuthorLab {
            get {
                return ResourceManager.GetString("AuthorLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný AuthorizationType.
        /// </summary>
        internal static string AuthType {
            get {
                return ResourceManager.GetString("AuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný BackToLabList.
        /// </summary>
        internal static string BackToLabList {
            get {
                return ResourceManager.GetString("BackToLabList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Backup Delete Failed.
        /// </summary>
        internal static string BackupDeleteFailed {
            get {
                return ResourceManager.GetString("BackupDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Backup Delete Fail Not Owned.
        /// </summary>
        internal static string BackupDeleteFailNotOwned {
            get {
                return ResourceManager.GetString("BackupDeleteFailNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Backup Delete Success.
        /// </summary>
        internal static string BackupDeleteSuccess {
            get {
                return ResourceManager.GetString("BackupDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Backup Download Failed.
        /// </summary>
        internal static string BackupDownloadFailed {
            get {
                return ResourceManager.GetString("BackupDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný BackupFailed.
        /// </summary>
        internal static string BackupFailed {
            get {
                return ResourceManager.GetString("BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný BackupLab.
        /// </summary>
        internal static string BackupLab {
            get {
                return ResourceManager.GetString("BackupLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Restore Failed.
        /// </summary>
        internal static string BackupRestoreFailed {
            get {
                return ResourceManager.GetString("BackupRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Backup Restore Fail Not Owned.
        /// </summary>
        internal static string BackupRestoreFailNotOwned {
            get {
                return ResourceManager.GetString("BackupRestoreFailNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Restore Success.
        /// </summary>
        internal static string BackupRestoreSuccess {
            get {
                return ResourceManager.GetString("BackupRestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Backupo.
        /// </summary>
        internal static string BackupsLayout {
            get {
                return ResourceManager.GetString("BackupsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Backup Success.
        /// </summary>
        internal static string BackupSuccess {
            get {
                return ResourceManager.GetString("BackupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CancelB.
        /// </summary>
        internal static string CancelB {
            get {
                return ResourceManager.GetString("CancelB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ChangePass.
        /// </summary>
        internal static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Not Supported.
        /// </summary>
        internal static string ChangePassLDAP {
            get {
                return ResourceManager.GetString("ChangePassLDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Closed.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ConfirmNewPass.
        /// </summary>
        internal static string ConfirmNewPass {
            get {
                return ResourceManager.GetString("ConfirmNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Connectos.
        /// </summary>
        internal static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ConnectionFailed.
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ConnectionLost.
        /// </summary>
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ConnectionSuccess.
        /// </summary>
        internal static string ConnectionSuccess {
            get {
                return ResourceManager.GetString("ConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CreatedAt.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CurrentCollaborators.
        /// </summary>
        internal static string CurrentCollaborators {
            get {
                return ResourceManager.GetString("CurrentCollaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DeactivateB.
        /// </summary>
        internal static string DeactivateButton {
            get {
                return ResourceManager.GetString("DeactivateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DeleteB.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DeleteConfirmLab.
        /// </summary>
        internal static string DeleteConfirmLab {
            get {
                return ResourceManager.GetString("DeleteConfirmLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DeleteLab.
        /// </summary>
        internal static string DeleteLab {
            get {
                return ResourceManager.GetString("DeleteLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabDescription.
        /// </summary>
        internal static string DescriptionLab {
            get {
                return ResourceManager.GetString("DescriptionLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DownloadLab.
        /// </summary>
        internal static string DownloadLab {
            get {
                return ResourceManager.GetString("DownloadLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný EditServer.
        /// </summary>
        internal static string EditServer {
            get {
                return ResourceManager.GetString("EditServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ExpiredReservations.
        /// </summary>
        internal static string ExpiredReservations {
            get {
                return ResourceManager.GetString("ExpiredReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný WarningExpiredReserv.
        /// </summary>
        internal static string ExpiredResWarning {
            get {
                return ResourceManager.GetString("ExpiredResWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Exports.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný FileNotFound.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Fri.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný FromTime.
        /// </summary>
        internal static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný GeneralDetails .
        /// </summary>
        internal static string GeneralDetails {
            get {
                return ResourceManager.GetString("GeneralDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Homes.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Homik.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ImportLab.
        /// </summary>
        internal static string ImportLab {
            get {
                return ResourceManager.GetString("ImportLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný InvalidCredentials.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný InvalidTime.
        /// </summary>
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerURLIP.
        /// </summary>
        internal static string IPadd {
            get {
                return ResourceManager.GetString("IPadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Labs.
        /// </summary>
        internal static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lab Delete Error.
        /// </summary>
        internal static string LabDeleteError {
            get {
                return ResourceManager.GetString("LabDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabDeleteSuccess.
        /// </summary>
        internal static string LabDeleteSuccess {
            get {
                return ResourceManager.GetString("LabDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Labid.
        /// </summary>
        internal static string LabId {
            get {
                return ResourceManager.GetString("LabId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabImportSuccess.
        /// </summary>
        internal static string LabImportSuccess {
            get {
                return ResourceManager.GetString("LabImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabInfo.
        /// </summary>
        internal static string LabInfo {
            get {
                return ResourceManager.GetString("LabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabName.
        /// </summary>
        internal static string LabName {
            get {
                return ResourceManager.GetString("LabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabNodesError.
        /// </summary>
        internal static string LabNodesError {
            get {
                return ResourceManager.GetString("LabNodesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabNotSelected.
        /// </summary>
        internal static string LabNotSelected {
            get {
                return ResourceManager.GetString("LabNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabOwnedRemove.
        /// </summary>
        internal static string LabOwnedRemoved {
            get {
                return ResourceManager.GetString("LabOwnedRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabOwnedRemoveError.
        /// </summary>
        internal static string LabOwnedRemoveError {
            get {
                return ResourceManager.GetString("LabOwnedRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabOwnedSuccess.
        /// </summary>
        internal static string LabOwnedSuccess {
            get {
                return ResourceManager.GetString("LabOwnedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabOwners.
        /// </summary>
        internal static string LabOwners {
            get {
                return ResourceManager.GetString("LabOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabStartedSuccess.
        /// </summary>
        internal static string LabStartedSuccess {
            get {
                return ResourceManager.GetString("LabStartedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabStartError.
        /// </summary>
        internal static string LabStartError {
            get {
                return ResourceManager.GetString("LabStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabStopError.
        /// </summary>
        internal static string LabStopError {
            get {
                return ResourceManager.GetString("LabStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabStopped.
        /// </summary>
        internal static string LabStoppedSuccess {
            get {
                return ResourceManager.GetString("LabStoppedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LabWithIDNotFound.
        /// </summary>
        internal static string LabWithIDNotFound {
            get {
                return ResourceManager.GetString("LabWithIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ListView.
        /// </summary>
        internal static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný locales.
        /// </summary>
        internal static string localhost {
            get {
                return ResourceManager.GetString("localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Loginos.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Log ins.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Logoutos.
        /// </summary>
        internal static string LogoutLayout {
            get {
                return ResourceManager.GetString("LogoutLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ManageBackup.
        /// </summary>
        internal static string ManageBackup {
            get {
                return ResourceManager.GetString("ManageBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ManageCollaborators.
        /// </summary>
        internal static string ManageCollaborators {
            get {
                return ResourceManager.GetString("ManageCollaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Manages User.
        /// </summary>
        internal static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný MessageWarningDeleteBackup.
        /// </summary>
        internal static string MessageWarningDeleteBackup {
            get {
                return ResourceManager.GetString("MessageWarningDeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný MessageWarningRestoreBackup.
        /// </summary>
        internal static string MessageWarningRestoreBackup {
            get {
                return ResourceManager.GetString("MessageWarningRestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ModifiedLab.
        /// </summary>
        internal static string ModifiedLab {
            get {
                return ResourceManager.GetString("ModifiedLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Mon.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný MonthView.
        /// </summary>
        internal static string MonthView {
            get {
                return ResourceManager.GetString("MonthView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Laboratos.
        /// </summary>
        internal static string MyLabLayout {
            get {
                return ResourceManager.GetString("MyLabLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný MyReserv.
        /// </summary>
        internal static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Names.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NewPass.
        /// </summary>
        internal static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NewReserv.
        /// </summary>
        internal static string NewReservation {
            get {
                return ResourceManager.GetString("NewReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NoBackups.
        /// </summary>
        internal static string NoBackups {
            get {
                return ResourceManager.GetString("NoBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NoCollaboratorsYet.
        /// </summary>
        internal static string NoCollaboratorsYet {
            get {
                return ResourceManager.GetString("NoCollaboratorsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NodesCount.
        /// </summary>
        internal static string NodesCount {
            get {
                return ResourceManager.GetString("NodesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NoExpired.
        /// </summary>
        internal static string NoExpired {
            get {
                return ResourceManager.GetString("NoExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NoLabsFound.
        /// </summary>
        internal static string NoLabsFound {
            get {
                return ResourceManager.GetString("NoLabsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NooneOwns.
        /// </summary>
        internal static string NoneOwns {
            get {
                return ResourceManager.GetString("NoneOwns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NoOwnedLab.
        /// </summary>
        internal static string NoOwnedLab {
            get {
                return ResourceManager.GetString("NoOwnedLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NoReservations.
        /// </summary>
        internal static string NoReservation {
            get {
                return ResourceManager.GetString("NoReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Oldpass.
        /// </summary>
        internal static string OldPass {
            get {
                return ResourceManager.GetString("OldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný OldPassIcorrect.
        /// </summary>
        internal static string OldPassIcorrect {
            get {
                return ResourceManager.GetString("OldPassIcorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný OwnLab.
        /// </summary>
        internal static string OwnLab {
            get {
                return ResourceManager.GetString("OwnLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Passwordo.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PasswordChanged.
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PasswordError.
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PasswordNotMatch.
        /// </summary>
        internal static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PasswordRequired.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PasswordPlaceholder.
        /// </summary>
        internal static string placeholderPass {
            get {
                return ResourceManager.GetString("placeholderPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PlannedReserv.
        /// </summary>
        internal static string PlannedReservations {
            get {
                return ResourceManager.GetString("PlannedReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PlatformSpecifics.
        /// </summary>
        internal static string PlatformSpecifics {
            get {
                return ResourceManager.GetString("PlatformSpecifics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RemoveCollab.
        /// </summary>
        internal static string RemoveCollab {
            get {
                return ResourceManager.GetString("RemoveCollab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RemoveOwnership.
        /// </summary>
        internal static string RemoveOwnership {
            get {
                return ResourceManager.GetString("RemoveOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ReservationCreated.
        /// </summary>
        internal static string ReservationCreated {
            get {
                return ResourceManager.GetString("ReservationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ReservationDeleted.
        /// </summary>
        internal static string ReservationDeleted {
            get {
                return ResourceManager.GetString("ReservationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ReservationExistsError.
        /// </summary>
        internal static string ReservationExistsError {
            get {
                return ResourceManager.GetString("ReservationExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reservioos.
        /// </summary>
        internal static string ReservationLayout {
            get {
                return ResourceManager.GetString("ReservationLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ReserveLab.
        /// </summary>
        internal static string ReserveLab {
            get {
                return ResourceManager.GetString("ReserveLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reservation must be at least 1 hour.aaaaa.
        /// </summary>
        internal static string ResOneHour {
            get {
                return ResourceManager.GetString("ResOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reservation start and end must be on the same dayyyy.
        /// </summary>
        internal static string ResSameDay {
            get {
                return ResourceManager.GetString("ResSameDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Roles.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sat.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SaveChanges.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SelectLab.
        /// </summary>
        internal static string SelectLab {
            get {
                return ResourceManager.GetString("SelectLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SelectPlatform.
        /// </summary>
        internal static string SelectPlatform {
            get {
                return ResourceManager.GetString("SelectPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SelectServer.
        /// </summary>
        internal static string SelectServer {
            get {
                return ResourceManager.GetString("SelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SelectView.
        /// </summary>
        internal static string SelectView {
            get {
                return ResourceManager.GetString("SelectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Servers.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerAddSuccess.
        /// </summary>
        internal static string ServerAdded {
            get {
                return ResourceManager.GetString("ServerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerName.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerNotAdded.
        /// </summary>
        internal static string ServerNotAdded {
            get {
                return ResourceManager.GetString("ServerNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServenNotExist.
        /// </summary>
        internal static string ServerNotExist {
            get {
                return ResourceManager.GetString("ServerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerNotFound.
        /// </summary>
        internal static string ServerNotFound {
            get {
                return ResourceManager.GetString("ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerNotSelected.
        /// </summary>
        internal static string ServerNotSelected {
            get {
                return ResourceManager.GetString("ServerNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerNotUpdated.
        /// </summary>
        internal static string ServerNotUpdated {
            get {
                return ResourceManager.GetString("ServerNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerOffline.
        /// </summary>
        internal static string ServerOffline {
            get {
                return ResourceManager.GetString("ServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerRemoved.
        /// </summary>
        internal static string ServerRemoved {
            get {
                return ResourceManager.GetString("ServerRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerTypos.
        /// </summary>
        internal static string ServerType {
            get {
                return ResourceManager.GetString("ServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ServerUpdated.
        /// </summary>
        internal static string ServerUpdated {
            get {
                return ResourceManager.GetString("ServerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Settingo.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ShowNodes.
        /// </summary>
        internal static string ShowNodes {
            get {
                return ResourceManager.GetString("ShowNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SomethingWriong.
        /// </summary>
        internal static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný StartedState.
        /// </summary>
        internal static string StartedState {
            get {
                return ResourceManager.GetString("StartedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný StartLab.
        /// </summary>
        internal static string StartLab {
            get {
                return ResourceManager.GetString("StartLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Statos.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný StopLab.
        /// </summary>
        internal static string StopLab {
            get {
                return ResourceManager.GetString("StopLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný StoppedState.
        /// </summary>
        internal static string StoppedState {
            get {
                return ResourceManager.GetString("StoppedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sun.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný TestConnection.
        /// </summary>
        internal static string TestConn {
            get {
                return ResourceManager.GetString("TestConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Thu.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ToTime.
        /// </summary>
        internal static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tue.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UnknownState.
        /// </summary>
        internal static string UnknownState {
            get {
                return ResourceManager.GetString("UnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UnsupportedPlatform.
        /// </summary>
        internal static string UnsupportedPlatform {
            get {
                return ResourceManager.GetString("UnsupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Users.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserActivated.
        /// </summary>
        internal static string UserActivated {
            get {
                return ResourceManager.GetString("UserActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserActivatedFail.
        /// </summary>
        internal static string UserActivatedFail {
            get {
                return ResourceManager.GetString("UserActivatedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserAddedFail.
        /// </summary>
        internal static string UserAddedFail {
            get {
                return ResourceManager.GetString("UserAddedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserAddedSuccess.
        /// </summary>
        internal static string UserAddedSuccess {
            get {
                return ResourceManager.GetString("UserAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserCollaboratorAdded.
        /// </summary>
        internal static string UserCollaboratorAdded {
            get {
                return ResourceManager.GetString("UserCollaboratorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserDeactivated.
        /// </summary>
        internal static string UserDeactivated {
            get {
                return ResourceManager.GetString("UserDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserDeactivatedFail.
        /// </summary>
        internal static string UserDeactivatedFail {
            get {
                return ResourceManager.GetString("UserDeactivatedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Usernamo.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserNotFound.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserNotSelected.
        /// </summary>
        internal static string UserNotSelected {
            get {
                return ResourceManager.GetString("UserNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserRemoved.
        /// </summary>
        internal static string UserRemoved {
            get {
                return ResourceManager.GetString("UserRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UserRemovedFail.
        /// </summary>
        internal static string UserRemovedFail {
            get {
                return ResourceManager.GetString("UserRemovedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Wed.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný YouNeedPassword.
        /// </summary>
        internal static string YouNeedPassword {
            get {
                return ResourceManager.GetString("YouNeedPassword", resourceCulture);
            }
        }
    }
}
