//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetResVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetResVM.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actionss.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivateB.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCollaboratorUsername.
        /// </summary>
        internal static string addcollabenterusername {
            get {
                return ResourceManager.GetString("addcollabenterusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCollaborator.
        /// </summary>
        internal static string AddCollaborator {
            get {
                return ResourceManager.GetString("AddCollaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddNewServer.
        /// </summary>
        internal static string AddNewServ {
            get {
                return ResourceManager.GetString("AddNewServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add HIM.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorLab.
        /// </summary>
        internal static string AuthorLab {
            get {
                return ResourceManager.GetString("AuthorLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizationType.
        /// </summary>
        internal static string AuthType {
            get {
                return ResourceManager.GetString("AuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackToLabList.
        /// </summary>
        internal static string BackToLabList {
            get {
                return ResourceManager.GetString("BackToLabList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackupLab.
        /// </summary>
        internal static string BackupLab {
            get {
                return ResourceManager.GetString("BackupLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backupo.
        /// </summary>
        internal static string BackupsLayout {
            get {
                return ResourceManager.GetString("BackupsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelB.
        /// </summary>
        internal static string CancelB {
            get {
                return ResourceManager.GetString("CancelB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangePass.
        /// </summary>
        internal static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported.
        /// </summary>
        internal static string ChangePassLDAP {
            get {
                return ResourceManager.GetString("ChangePassLDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmNewPass.
        /// </summary>
        internal static string ConfirmNewPass {
            get {
                return ResourceManager.GetString("ConfirmNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectos.
        /// </summary>
        internal static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedAt.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeactivateB.
        /// </summary>
        internal static string DeactivateButton {
            get {
                return ResourceManager.GetString("DeactivateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteB.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteConfirmLab.
        /// </summary>
        internal static string DeleteConfirmLab {
            get {
                return ResourceManager.GetString("DeleteConfirmLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteLab.
        /// </summary>
        internal static string DeleteLab {
            get {
                return ResourceManager.GetString("DeleteLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabDescription.
        /// </summary>
        internal static string DescriptionLab {
            get {
                return ResourceManager.GetString("DescriptionLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadLab.
        /// </summary>
        internal static string DownloadLab {
            get {
                return ResourceManager.GetString("DownloadLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditServer.
        /// </summary>
        internal static string EditServer {
            get {
                return ResourceManager.GetString("EditServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiredReservations.
        /// </summary>
        internal static string ExpiredReservations {
            get {
                return ResourceManager.GetString("ExpiredReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarningExpiredReserv.
        /// </summary>
        internal static string ExpiredResWarning {
            get {
                return ResourceManager.GetString("ExpiredResWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromTime.
        /// </summary>
        internal static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralDetails .
        /// </summary>
        internal static string GeneralDetails {
            get {
                return ResourceManager.GetString("GeneralDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homes.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homik.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportLab.
        /// </summary>
        internal static string ImportLab {
            get {
                return ResourceManager.GetString("ImportLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerURLIP.
        /// </summary>
        internal static string IPadd {
            get {
                return ResourceManager.GetString("IPadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labs.
        /// </summary>
        internal static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labid.
        /// </summary>
        internal static string LabId {
            get {
                return ResourceManager.GetString("LabId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabInfo.
        /// </summary>
        internal static string LabInfo {
            get {
                return ResourceManager.GetString("LabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabName.
        /// </summary>
        internal static string LabName {
            get {
                return ResourceManager.GetString("LabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabOwners.
        /// </summary>
        internal static string LabOwners {
            get {
                return ResourceManager.GetString("LabOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView.
        /// </summary>
        internal static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locales.
        /// </summary>
        internal static string localhost {
            get {
                return ResourceManager.GetString("localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loginos.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log ins.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoutos.
        /// </summary>
        internal static string LogoutLayout {
            get {
                return ResourceManager.GetString("LogoutLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManageBackup.
        /// </summary>
        internal static string ManageBackup {
            get {
                return ResourceManager.GetString("ManageBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manages User.
        /// </summary>
        internal static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageWarningDeleteBackup.
        /// </summary>
        internal static string MessageWarningDeleteBackup {
            get {
                return ResourceManager.GetString("MessageWarningDeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageWarningRestoreBackup.
        /// </summary>
        internal static string MessageWarningRestoreBackup {
            get {
                return ResourceManager.GetString("MessageWarningRestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedLab.
        /// </summary>
        internal static string ModifiedLab {
            get {
                return ResourceManager.GetString("ModifiedLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthView.
        /// </summary>
        internal static string MonthView {
            get {
                return ResourceManager.GetString("MonthView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratos.
        /// </summary>
        internal static string MyLabLayout {
            get {
                return ResourceManager.GetString("MyLabLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyReserv.
        /// </summary>
        internal static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPass.
        /// </summary>
        internal static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewReserv.
        /// </summary>
        internal static string NewReservation {
            get {
                return ResourceManager.GetString("NewReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoBackups.
        /// </summary>
        internal static string NoBackups {
            get {
                return ResourceManager.GetString("NoBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodesCount.
        /// </summary>
        internal static string NodesCount {
            get {
                return ResourceManager.GetString("NodesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoExpired.
        /// </summary>
        internal static string NoExpired {
            get {
                return ResourceManager.GetString("NoExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NooneOwns.
        /// </summary>
        internal static string NoneOwns {
            get {
                return ResourceManager.GetString("NoneOwns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoOwnedLab.
        /// </summary>
        internal static string NoOwnedLab {
            get {
                return ResourceManager.GetString("NoOwnedLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoReservations.
        /// </summary>
        internal static string NoReservation {
            get {
                return ResourceManager.GetString("NoReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldpass.
        /// </summary>
        internal static string OldPass {
            get {
                return ResourceManager.GetString("OldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwnLab.
        /// </summary>
        internal static string OwnLab {
            get {
                return ResourceManager.GetString("OwnLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwordo.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordPlaceholder.
        /// </summary>
        internal static string placeholderPass {
            get {
                return ResourceManager.GetString("placeholderPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlannedReserv.
        /// </summary>
        internal static string PlannedReservations {
            get {
                return ResourceManager.GetString("PlannedReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlatformSpecifics.
        /// </summary>
        internal static string PlatformSpecifics {
            get {
                return ResourceManager.GetString("PlatformSpecifics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveOwnership.
        /// </summary>
        internal static string RemoveOwnership {
            get {
                return ResourceManager.GetString("RemoveOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservioos.
        /// </summary>
        internal static string ReservationLayout {
            get {
                return ResourceManager.GetString("ReservationLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReserveLab.
        /// </summary>
        internal static string ReserveLab {
            get {
                return ResourceManager.GetString("ReserveLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveChanges.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectLab.
        /// </summary>
        internal static string SelectLab {
            get {
                return ResourceManager.GetString("SelectLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectPlatform.
        /// </summary>
        internal static string SelectPlatform {
            get {
                return ResourceManager.GetString("SelectPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectServer.
        /// </summary>
        internal static string SelectServer {
            get {
                return ResourceManager.GetString("SelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectView.
        /// </summary>
        internal static string SelectView {
            get {
                return ResourceManager.GetString("SelectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerName.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerTypos.
        /// </summary>
        internal static string ServerType {
            get {
                return ResourceManager.GetString("ServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settingo.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowNodes.
        /// </summary>
        internal static string ShowNodes {
            get {
                return ResourceManager.GetString("ShowNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartedState.
        /// </summary>
        internal static string StartedState {
            get {
                return ResourceManager.GetString("StartedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartLab.
        /// </summary>
        internal static string StartLab {
            get {
                return ResourceManager.GetString("StartLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statos.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopLab.
        /// </summary>
        internal static string StopLab {
            get {
                return ResourceManager.GetString("StopLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoppedState.
        /// </summary>
        internal static string StoppedState {
            get {
                return ResourceManager.GetString("StoppedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestConnection.
        /// </summary>
        internal static string TestConn {
            get {
                return ResourceManager.GetString("TestConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToTime.
        /// </summary>
        internal static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnknownState.
        /// </summary>
        internal static string UnknownState {
            get {
                return ResourceManager.GetString("UnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usernamo.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
