//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetResVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetResVM.Resources.SharedResource.en", typeof(SharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username of the person you want to grant access to this lab.
        /// </summary>
        internal static string addcollabenterusername {
            get {
                return ResourceManager.GetString("addcollabenterusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add collaborator.
        /// </summary>
        internal static string AddCollaborator {
            get {
                return ResourceManager.GetString("AddCollaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new server.
        /// </summary>
        internal static string AddNewServ {
            get {
                return ResourceManager.GetString("AddNewServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string AuthorLab {
            get {
                return ResourceManager.GetString("AuthorLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization type.
        /// </summary>
        internal static string AuthType {
            get {
                return ResourceManager.GetString("AuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to lab list.
        /// </summary>
        internal static string BackToLabList {
            get {
                return ResourceManager.GetString("BackToLabList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Lab.
        /// </summary>
        internal static string BackupLab {
            get {
                return ResourceManager.GetString("BackupLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        internal static string BackupsLayout {
            get {
                return ResourceManager.GetString("BackupsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelB {
            get {
                return ResourceManager.GetString("CancelB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing password is not available for LDAP user.
        /// </summary>
        internal static string ChangePassLDAP {
            get {
                return ResourceManager.GetString("ChangePassLDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string ConfirmNewPass {
            get {
                return ResourceManager.GetString("ConfirmNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to server.
        /// </summary>
        internal static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string DeactivateButton {
            get {
                return ResourceManager.GetString("DeactivateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this lab?.
        /// </summary>
        internal static string DeleteConfirmLab {
            get {
                return ResourceManager.GetString("DeleteConfirmLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this lab.
        /// </summary>
        internal static string DeleteLab {
            get {
                return ResourceManager.GetString("DeleteLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab description.
        /// </summary>
        internal static string DescriptionLab {
            get {
                return ResourceManager.GetString("DescriptionLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Lab.
        /// </summary>
        internal static string DownloadLab {
            get {
                return ResourceManager.GetString("DownloadLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit server.
        /// </summary>
        internal static string EditServer {
            get {
                return ResourceManager.GetString("EditServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired reservations.
        /// </summary>
        internal static string ExpiredReservations {
            get {
                return ResourceManager.GetString("ExpiredReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired reservations are deleted automatically after 6 months.
        /// </summary>
        internal static string ExpiredResWarning {
            get {
                return ResourceManager.GetString("ExpiredResWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General details.
        /// </summary>
        internal static string GeneralDetails {
            get {
                return ResourceManager.GetString("GeneralDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server selection.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import lab.
        /// </summary>
        internal static string ImportLab {
            get {
                return ResourceManager.GetString("ImportLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address of server or URL.
        /// </summary>
        internal static string IPadd {
            get {
                return ResourceManager.GetString("IPadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        internal static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab ID.
        /// </summary>
        internal static string LabId {
            get {
                return ResourceManager.GetString("LabId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab info.
        /// </summary>
        internal static string LabInfo {
            get {
                return ResourceManager.GetString("LabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab name.
        /// </summary>
        internal static string LabName {
            get {
                return ResourceManager.GetString("LabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab owners.
        /// </summary>
        internal static string LabOwners {
            get {
                return ResourceManager.GetString("LabOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        internal static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localhost.
        /// </summary>
        internal static string localhost {
            get {
                return ResourceManager.GetString("localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login page.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogoutLayout {
            get {
                return ResourceManager.GetString("LogoutLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage backup.
        /// </summary>
        internal static string ManageBackup {
            get {
                return ResourceManager.GetString("ManageBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this backup? This operation is pernament!.
        /// </summary>
        internal static string MessageWarningDeleteBackup {
            get {
                return ResourceManager.GetString("MessageWarningDeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore this backup? This operation will overwrite the current lab state..
        /// </summary>
        internal static string MessageWarningRestoreBackup {
            get {
                return ResourceManager.GetString("MessageWarningRestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string ModifiedLab {
            get {
                return ResourceManager.GetString("ModifiedLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar View (current month).
        /// </summary>
        internal static string MonthView {
            get {
                return ResourceManager.GetString("MonthView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My labs.
        /// </summary>
        internal static string MyLabLayout {
            get {
                return ResourceManager.GetString("MyLabLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reservations.
        /// </summary>
        internal static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new reservation.
        /// </summary>
        internal static string NewReservation {
            get {
                return ResourceManager.GetString("NewReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backups found.
        /// </summary>
        internal static string NoBackups {
            get {
                return ResourceManager.GetString("NoBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node count.
        /// </summary>
        internal static string NodesCount {
            get {
                return ResourceManager.GetString("NodesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expired reservations available.
        /// </summary>
        internal static string NoExpired {
            get {
                return ResourceManager.GetString("NoExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoneOwns {
            get {
                return ResourceManager.GetString("NoneOwns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t own any labs yet..
        /// </summary>
        internal static string NoOwnedLab {
            get {
                return ResourceManager.GetString("NoOwnedLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No planned reservations.
        /// </summary>
        internal static string NoReservation {
            get {
                return ResourceManager.GetString("NoReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string OldPass {
            get {
                return ResourceManager.GetString("OldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own lab.
        /// </summary>
        internal static string OwnLab {
            get {
                return ResourceManager.GetString("OwnLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Leave blank to keep unchanged).
        /// </summary>
        internal static string placeholderPass {
            get {
                return ResourceManager.GetString("placeholderPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned reservations.
        /// </summary>
        internal static string PlannedReservations {
            get {
                return ResourceManager.GetString("PlannedReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Specifics.
        /// </summary>
        internal static string PlatformSpecifics {
            get {
                return ResourceManager.GetString("PlatformSpecifics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ownership.
        /// </summary>
        internal static string RemoveOwnership {
            get {
                return ResourceManager.GetString("RemoveOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        internal static string ReservationLayout {
            get {
                return ResourceManager.GetString("ReservationLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve this lab.
        /// </summary>
        internal static string ReserveLab {
            get {
                return ResourceManager.GetString("ReserveLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select lab....
        /// </summary>
        internal static string SelectLab {
            get {
                return ResourceManager.GetString("SelectLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select platform.
        /// </summary>
        internal static string SelectPlatform {
            get {
                return ResourceManager.GetString("SelectPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select server....
        /// </summary>
        internal static string SelectServer {
            get {
                return ResourceManager.GetString("SelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select view.
        /// </summary>
        internal static string SelectView {
            get {
                return ResourceManager.GetString("SelectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string ServerType {
            get {
                return ResourceManager.GetString("ServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show nodes.
        /// </summary>
        internal static string ShowNodes {
            get {
                return ResourceManager.GetString("ShowNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string StartedState {
            get {
                return ResourceManager.GetString("StartedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start this lab.
        /// </summary>
        internal static string StartLab {
            get {
                return ResourceManager.GetString("StartLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop this lab.
        /// </summary>
        internal static string StopLab {
            get {
                return ResourceManager.GetString("StopLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string StoppedState {
            get {
                return ResourceManager.GetString("StoppedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        internal static string TestConn {
            get {
                return ResourceManager.GetString("TestConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknownState {
            get {
                return ResourceManager.GetString("UnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
